# Generated by Django 5.2.8 on 2025-12-02 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0005_rename_questionid_option_questionfk'),
        ('users', '0002_rename_users_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptAssessment',
            fields=[
                ('AttemptID', models.AutoField(primary_key=True, serialize=False)),
                ('SubmittedAt', models.DateTimeField(auto_now=True)),
                ('AssessmentFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessment')),
                ('UserFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='AttemptQuestion',
            fields=[
                ('AttemptQuestionID', models.AutoField(primary_key=True, serialize=False)),
                ('Question', models.CharField()),
                ('AttemptFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attempts.attemptassessment')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('OptionID', models.AutoField(primary_key=True, serialize=False)),
                ('Option', models.CharField()),
                ('isCorrect', models.BooleanField()),
                ('isChosen', models.BooleanField()),
                ('AttemptQuestionFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attempts.attemptquestion')),
            ],
        ),
    ]
