# Generated by Django 5.2.8 on 2025-12-02 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptOption',
            fields=[
                ('AttemptOptionID', models.AutoField(primary_key=True, serialize=False)),
                ('Option', models.CharField()),
                ('isCorrect', models.BooleanField()),
                ('isChosen', models.BooleanField()),
                ('AttemptQuestionFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attempts.attemptquestion')),
            ],
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
