# Generated by Django 5.2.8 on 2025-12-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0002_attemptoption_delete_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptassessment',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attemptassessment',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
