# Generated by Django 5.2.8 on 2025-12-04 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0003_attemptassessment_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attemptassessment',
            old_name='score',
            new_name='Score',
        ),
        migrations.RenameField(
            model_name='attemptassessment',
            old_name='total_score',
            new_name='TotalScore',
        ),
    ]
