# Generated by Django 5.2.8 on 2025-12-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField()),
                ('Email', models.EmailField(max_length=254)),
                ('Hashed_Password', models.CharField()),
                ('Phone', models.CharField()),
                ('Role', models.CharField(choices=[('Student', 'Student'), ('Admin', 'Admin')])),
                ('Grade', models.CharField(choices=[('G13', 'G13'), ('G14', 'G14')])),
            ],
        ),
    ]
