# Generated by Django 5.2.8 on 2025-12-02 11:42

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_users_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.EmailField(max_length=254, unique=True, validators=[users.validators.validate_email]),
        ),
    ]
