# Generated by Django 5.2.8 on 2025-12-02 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Grade',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Hashed_Password',
            new_name='hashed_password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Role',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UserID',
            new_name='userID',
        ),
    ]
