# Generated by Django 5.2.8 on 2025-12-02 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_email_user_email_rename_grade_user_grade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userID',
            new_name='id',
        ),
    ]
