# Generated by Django 5.2.8 on 2025-12-04 06:26

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_userid_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(unique=True, validators=[users.validators.validate_email]),
        ),
        migrations.AlterField(
            model_name='user',
            name='hashed_password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=16, validators=[users.validators.validate_phone]),
        ),
    ]
