# Generated by Django 5.2.8 on 2025-12-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('AssessmentID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('Duration', models.DurationField()),
                ('Subject', models.CharField(choices=[('Math', 'Math'), ('Arabic', 'Arabic'), ('Physics', 'Physics'), ('English', 'English'), ('Flutter', 'Flutter'), ('Data Science', 'Data Science')], max_length=20)),
                ('Grade', models.CharField(choices=[('g13', 'Grade 13'), ('g14', 'Grade 14')], max_length=20)),
            ],
        ),
    ]
