# Generated by Django 5.2.8 on 2025-12-01 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='Grade',
            field=models.CharField(choices=[('G13', 'G13'), ('G14', 'G14')], max_length=20),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('QuestionID', models.AutoField(primary_key=True, serialize=False)),
                ('Question', models.CharField(max_length=200)),
                ('AssessmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('OptionID', models.AutoField(primary_key=True, serialize=False)),
                ('Option', models.CharField()),
                ('isCorrect', models.BooleanField()),
                ('QuestionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.question')),
            ],
        ),
    ]
