# Generated by Django 5.2.8 on 2025-12-02 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_rename_options_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='AssessmentID',
            new_name='AssessmentFk',
        ),
    ]
