# Generated by Django 5.2.8 on 2025-12-02 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_rename_assessmentid_question_assessmentfk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='QuestionID',
            new_name='QuestionFk',
        ),
    ]
